### ISSUE TITLE
I'm a noob and can't run code at all

### ISSUE THREAD

**Issue by Zer013teen** [Starwort/tripeak_solver#1]
I think I compiled\built it correctly but when I try to run it it looks like this:

C:\Users\Zer013teen\Desktop\tripeak_solver-master>cargo run
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.08s
     Running `target\debug\tripeak.exe`
thread 'main' panicked at src/main.rs:269:5:
Not enough cards provided
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\tripeak.exe` (exit code: 101)

**Comment by Starwort** [comment]
You need to pass the cards you're trying to solve as the next parameters to `cargo run` - See [Courtney Pitcher's README](https://github.com/IgniparousTempest/javascript-tri-peaks-solitaire-solver) for more information; for her example you would be using the command `cargo r 8S TS 4D 7S 5D 7C 2D JH AC 3S 2H 3H 9H KC QC TD 8D 9C 7H 9D JS QS 4H 5C 5S 4C 2C QD 8C KD 3D KS JD 2S 7D KH AH 5H 9S 4S QH 6S 6D 3C JC TC 8H 6C TH AS AD 6H`

**Comment by Zer013teen** [comment]
Apparently the board I'm trying to solve is impossible because it freezes every solver
![impossible boards](https://github.com/user-attachments/assets/0d4be7e3-315f-4642-af2c-82140fbd2ab1)
